### ISSUE TITLE
Error on lektor_s3.py line 144

### ISSUE THREAD

**Issue by rolojf** [spenczar/lektor-s3#22]
> Finished build in 0.03 sec
Started prune
D...
Finished prune in 0.44 sec
]$ lektor deploy s3
Deploying to S3
  Build cache: /home/rolo/.cache/lektor/builds/28663b89a9d6aed2ce83cab679af2035
  Target: s3://www.xyz.mx
Traceback (most recent call last):
  File "/usr/bin/lektor", line 11, in <module>
    load_entry_point('Lektor==3.1.1', 'console_scripts', 'lektor')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lektor/cli.py", line 342, in deploy_cmd
    for line in event_iter:
  File "/home/rolo/.cache/lektor/packages/141f7b7097af990e1647ba986a7a22c6/lektor_s3.py", line 250, in publish
    diff = self.compute_diff(local, remote)
  File "/home/rolo/.cache/lektor/packages/141f7b7097af990e1647ba986a7a22c6/lektor_s3.py", line 144, in compute_diff
    key = posixify(self.key_prefix + f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
]$

Looking around on the internet saw that this error is presented when tried to encode twice the same string.  I don't know, too noob on python.  Please help.

**Comment by rolojf** [comment]
Not working on Lektor anymore. Cheers
