### ISSUE TITLE
Won't install in python 3.11.2 in ubuntu 23.04

### ISSUE THREAD

**Issue by transplier** [spenczar/lektor-s3#25]
I'm not enough of a Python expert to debug much further, but running `lektor build` on a project with lektor-s3 enabled throws this error:

```
g@hamilton:~/share/Sites/giferrari.net$ lektor serve
Traceback (most recent call last):
  File "/home/g/.local/bin/lektor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/lektor/cli.py", line 622, in main
    cli.main(args=args, prog_name=name)
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/lektor/cli.py", line 342, in server_cmd
    ctx.load_plugins(extra_flags=extra_flags)
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/lektor/cli_utils.py", line 140, in load_plugins
    initialize_plugins(self.get_env())
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/lektor/pluginsystem.py", line 128, in initialize_plugins
    plugins = load_plugins()
              ^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages/lektor/pluginsystem.py", line 122, in load_plugins
    rv[ep.name] = ep.load()
                  ^^^^^^^^^
  File "/home/g/.local/pipx/shared/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2516, in load
    self.require(*args, **kwargs)
  File "/home/g/.local/pipx/shared/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2539, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/shared/lib/python3.11/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/g/.local/pipx/shared/lib/python3.11/site-packages/pkg_resources/__init__.py", line 873, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 2.0.3 (/home/g/.local/pipx/venvs/lektor/lib/python3.11/site-packages), Requirement.parse('urllib3<1.27,>=1.25.4'), {'botocore'})
```
Seems there is a version conflict in urllib3. I'm running this in a brand new pipx venv.

**Comment by AL-255** [comment]
Same issue
