### ISSUE TITLE
0.3.0 not found

### ISSUE THREAD

**Issue by brettc** [spenczar/lektor-s3#7]
Only just starting with lektor, so perhaps I'm missing something but:

```
 ❯ lektor plugins add lektor-s3
Package lektor-s3 (0.3.0) was added to the project

 ❯ lektor deploy
Updating packages in /Users/brett/Library/Caches/Lektor/packages/e0ff65c242691dc50d88058ec46f04b5 for project
Collecting lektor-s3==0.3.0
  Could not find a version that satisfies the requirement lektor-s3==0.3.0 (from versions: 0.1, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3)
No matching distribution found for lektor-s3==0.3.0
Traceback (most recent call last):
  File "/Users/brett/anaconda/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/Users/brett/anaconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brett/anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/lektor/cli.py", line 264, in deploy_cmd
    ctx.load_plugins()
  File "/Users/brett/anaconda/lib/python2.7/site-packages/lektor/cli.py", line 89, in load_plugins
    load_packages(self.get_env(), reinstall=reinstall)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/lektor/packages.py", line 303, in load_packages
    refresh=reinstall)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/lektor/packages.py", line 273, in update_cache
    download_and_install_package(package_root, package, version)
  File "/Users/brett/anaconda/lib/python2.7/site-packages/lektor/packages.py", line 102, in download_and_install_package
    raise RuntimeError('Failed to install dependency package.')
RuntimeError: Failed to install dependency package.
```

**Comment by spenczar** [comment]
Thanks for reporting this. Something got garbled in the most recent push to PyPi.

Please try again - this should be resolved. If it isn't, reopen this issue.

**Comment by brettc** [comment]
Thanks for the speedy fix --- that did the trick!
